services:
  mariadb:
    image: mariadb:10.6
    command: [
      "mysqld",
      "--innodb-buffer-pool-size=8G",
      "--innodb-flush-log-at-trx-commit=2"
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  suitecrm:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  mariadb_data:

